### ISSUE TITLE
RFE: add options for ITR and ZTR to RHBugzilla

### ISSUE THREAD

**Issue by pkubatrh** [python-bugzilla/python-bugzilla#100]
Seems like the fields can already be set via the cli `--fields` option, but it would be nice to be able to set them by a call to `build_{createbug,update}` as well.

ITR field name is `cf_internal_target_release` and ZTR field name is `cf_zstream_target_release`

**Comment by crobinso** [comment]
Thanks for the suggestion, but 'cf_' fields are custom fields added by bugzilla instances. I don't want to add any more of those to the cli or API because it's basically a never ending slippery slope. So --fields or manually altering the update/createbug dictionary is the solution

**Comment by pkubatrh** [comment]
Makes sense.

Will try the dict alter method you mentioned in my app and see if it works for me, thanks!
