### ISSUE TITLE
[RFE] Add coroutines (asyncio) support

### ISSUE THREAD

**Issue by hroncok** [python-bugzilla/python-bugzilla#101]
I'd like to use Python to talk to Bugzilla from a coroutine. Currently, python-bugzilla uses [xmlrpc.client](https://docs.python.org/3/library/xmlrpc.client.html) and every call to Bugzilla is blocking. This is an RFC to also allow async operations. Maybe via [aiohttp-xmlrpc](https://pypi.org/project/aiohttp-xmlrpc/).

Currently I can get around this problem by using [asyncio.loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) like this:

```python
def _bugzillas():
    bzapi = bugzilla.Bugzilla(BUGZILLA)
    query = bzapi.build_query(product='Fedora')
    query['blocks'] = TRACKER
    return sorted(bzapi.query(query), key=lambda b: -b.id)


async def bugzillas():
    loop = asyncio.get_event_loop()
    with concurrent.futures.ThreadPoolExecutor() as pool:
        return await loop.run_in_executor(pool, _bugzillas)
```

Thanks for considering.

**Comment by crobinso** [comment]
Interesting, thanks for the suggestion. FWIW upstream bugzilla XMLRPC is deprecated and REST is the official supported API going forward. python-bugzilla doesn't support it yet but we will eventually. Not sure if/how that would affect this.

**Comment by hroncok** [comment]
Either way, the underlying HTTP must be async to support async on top. If it is xmlrpc or REST is not that important.

**Comment by crobinso** [comment]
@hroncok bugzilla in git has a way to pass in a requests.Session instance that we will use to handle all HTTP traffic. Does that help in any way?

**Comment by hroncok** [comment]
I don't think so. Even if an "asyncio requests session drop-in replacement" would be possible, you would still need to change the way you do the requests from sync to async and make your Python API async.

**Comment by hroncok** [comment]
BTW Checkout https://www.python-httpx.org/ for a nice requests replacement for asyncio.

**Comment by crobinso** [comment]
If someone is motivated to work on this I will help test and review it but I have no plans to work on this for the foreseeable future
