### ISSUE TITLE
xmlrpc.client.Fault: <Fault -32000: 'Can\'t call method "sub_component_count" on an undefined value at /var/www/html/bugzilla/extensions/SubComponents/Extension.pm line 931.\n'>

### ISSUE THREAD

**Issue by Zlopez** [python-bugzilla/python-bugzilla#102]
Hi, 

I'm currently having this issue when trying to call `createbug` method.

Here is the full traceback: [the-new-hotness-46.log](https://github.com/python-bugzilla/python-bugzilla/files/3382149/the-new-hotness-46.log)

**Comment by crobinso** [comment]
This looks like it's coming from deep inside bugzilla. I suggest filing a bug against bugzilla.redhat.com, Classification=Community Product=Bugzilla. They will want to know the full data you are passing to createbug
