### ISSUE TITLE
URL parsing issues

### ISSUE THREAD

**Issue by mslacken** [python-bugzilla/python-bugzilla#109]
When using 
my_api = bugzilla.Bugzilla("partner-bugzilla.redhat.com")
one will get:
 raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:///partner-bugzilla.redhat.com': No host supplied
Note the https:/// which should be https://
As workarround
my_api = bugzilla.Bugzilla("https://partner-bugzilla.redhat.com")
can be used.

**Comment by crobinso** [comment]
Thanks for the report. This regressed recently with a cleanup patch. Fixed upstream now, with tests added
