### ISSUE TITLE
Listing the users in a group

### ISSUE THREAD

**Issue by pypingou** [python-bugzilla/python-bugzilla#111]
I'm trying to figure a way to list all the users in a group. So I've added an Group object to python-bugzilla, I'm able to query bugzilla for a specific group or search for them (very similar to how we support User), but I'm failing to find the way to query bugzilla for the list of members.

Would you have any pointers for this?

I can send a PR with what I already have if it's interesting.

**Comment by pypingou** [comment]
Here is my work in progress:
https://github.com/python-bugzilla/python-bugzilla/compare/master...pypingou:start_group_support

**Comment by crobinso** [comment]
here's the bugzilla API for Groups. There's a `get` API that may do what you want: https://bugzilla.readthedocs.io/en/5.0/api/core/v1/group.html

That's for bugzilla 5.0, but I'm not sure it's REST only or for XMLRPC that python-bugzilla presently only supports. You can try Groups.get(XXX) and see if that works

**Comment by pypingou** [comment]
I dug around until I found that API doc (I was finding the one for 4.4 much more easily), but with that documentation, I could figure a way to get what I wanted which is what is submitted in: https://github.com/python-bugzilla/python-bugzilla/pull/112 for your consideration :)

**Comment by pypingou** [comment]
I've just checked the API you've added and it gives us the information we're looking for, thanks!
