### ISSUE TITLE
Retrieve if a component is_active or not

### ISSUE THREAD

**Issue by pypingou** [python-bugzilla/python-bugzilla#114]
We can easily mark a component as active or not by simply using the ``is_active`` argument on ``...editcomponent()``, however, I'm struggling to find how to retrieve if a component is active or not.

``..._proxy.Component.get({'names': ...})`` doesn't seem to return this information.

Any hint?

**Comment by crobinso** [comment]
Indeed it doesn't seem to return that information. Component.get is a bugzilla.redhat.com extension, you can see the info it returns here: https://bugzilla.redhat.com/docs/en/html/integrating/api/Bugzilla/Extension/RedHat/WebService/Component.html#get-components

The upstream bugzilla way of getting component info is via Product.get, which does return `is_active` info. Example:

```python
import pprint                                                                    
import bugzilla                                                                  
                                                                                 
bzapi = bugzilla.Bugzilla("bugzilla.redhat.com")                                 
ret = bzapi.product_get(                                                         
    names=["Virtualization Tools"],                                              
    include_fields=["name", "components.name", "components.is_active"])          
pprint.pprint(ret)
```

```console
$ python3 test.py
[{'components': [{'is_active': True, 'name': 'hivex'},
                 {'is_active': True, 'name': 'libguestfs'},
                 {'is_active': False, 'name': 'libosinfo'},
                 ...
  'name': 'Virtualization Tools'}]
```
Unfortunately running that on `Fedora` product takes 10-25 seconds, and there's no way that I know of to limit the query to a single component.

RHBZ admins are pretty responsive to feature extensions though, so if the Product.get way is a problem, you could file a request with them to expose `is_active` info via Component.get

**Comment by crobinso** [comment]
@pypingou Also if I can make a request from you: if you know of places in Fedora infrastructure that are using `_proxy` directly, please file issues here to get those APIs exposed in python-bugzilla. If at some point in the future bugzilla.redhat.com drops the XMLRPC API in favor of the REST API, any direct _proxy usage is going to break. I don't expect that to happen for a long time, maybe not ever, but better to get those issues sorted out either way

**Comment by pypingou** [comment]
I'm trying to use this API instead of the _proxy one, waiting for a sew seconds is not a problem and we in fact want all the components most of the time so that's fine.

However, the doc at: https://bugzilla.redhat.com/docs/en/html/integrating/api/Bugzilla/Extension/RedHat/WebService/Component.html#get-components mention ``default_cc`` but regardless of whether I specify it in ``include_fields`` or not have an ``include_fields`` entirely, I'm not getting the CC list in return. Am I missing something or is this something in bugzilla?

If you're curious this is the code-base I'm trying to get working: https://pagure.io/Fedora-Infra/distgit-bugzilla-sync/blob/master/f/distgit_bugzilla_sync/script.py#_158

**Comment by crobinso** [comment]
Those docs and that API (_proxy.Component.get) are bugzilla.redhat.com custom extensions. The code I posted about is for Product.get, which is a standard bugzilla API. The fields that Product.get returns are here: https://bugzilla.redhat.com/docs/en/html/api/core/v1/product.html#get-product

Unfortunately it looks like Product.get doesn't return the default_cc list, which is bogus, considering that the official Component.update API for upstream bugzilla allows altering it: https://bugzilla.readthedocs.io/en/latest/api/core/v1/component.html#update-component

I filed this bug against bugzilla.redhat.com to get some clarification, please follow along there: https://bugzilla.redhat.com/show_bug.cgi?id=1791324
