### ISSUE TITLE
How to set multiple needinfo flags?

### ISSUE THREAD

**Issue by ignatenkobrain** [python-bugzilla/python-bugzilla#118]
```
ipdb> bz.update_bugs([bug.id], bz.build_update(flags=[{"requestee": bug.assigned_to, "name": "needinfo", "status": "?"}]))                                                                                                                    
*** xmlrpc.client.Fault: <Fault 132: "The flag 'needinfo' has been set multiple times. You must specify the id value to update the flag.">
```

I have tried various tricks with trying to set it, but no luck. Basically everything what I want is to set additional needinfo flag which is definitely possible via webui (on bugzilla.redhat.com).

**Comment by crobinso** [comment]
I didn't know offhand but from the bugzilla API docs:

https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#update-bug

The flag section at the end says that when setting multiple flags of the same type you need to specify the internal type_id value of the flag in question. On partner-bugzilla.redhat.com it looks like the needinfo type_id is 16. So try dropping `"name": "needinfo"` and use `"type_id": 16` and see if that works (I didn't confirm for myself)

**Comment by crobinso** [comment]
Closing this, please reopen if you can't get it to work

**Comment by sferich888** [comment]
I recently hit his issue running a script. It seems to happen when needinfo is already set on a bug and you are adding another request for need info.

**Comment by esposem** [comment]
Apparently the solution is to set `"new" : True` in the flag, as explained at the end of https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#update-bug
