### ISSUE TITLE
Upcoming release?

### ISSUE THREAD

**Issue by pypingou** [python-bugzilla/python-bugzilla#120]
Hi @crobinso 

I know you were busy with some things and wanted to chime in a few more changes before doing a release, but I am curious if you have any rough ETA for the next release?

I'd like to make use of the Group support we've recently added :)

Thanks!

**Comment by crobinso** [comment]
Thanks for the reminder. I released v2.4.0 now, I'll do Fedora + EPEL builds shortly

**Comment by pypingou** [comment]
Thank you ! :)
