### ISSUE TITLE
'rst2man' is not the correct executable name

### ISSUE THREAD

**Issue by mgorny** [python-bugzilla/python-bugzilla#121]
The setup.py script attempts to build manpages through calling `rst2man`. However, there is no such program on Gentoo Linux:

```
python3.6 setup.py build -j 12
running build
sh: rst2man: command not found
Generating man/bugzilla.1
Generating 'man/bugzilla.1' failed.
```

The correct executable is `rst2man.py`. I'm guessing that your distribution renames it.

**Comment by crobinso** [comment]
Thanks for the report. I thought pip didn't install any binary for it, got confused by Fedora renaming things here, so thanks for explaining. Should be fixed in git now, I'll do another release today or tomorrow
