### ISSUE TITLE
_init_class_from_url breaks inheritance for RHBugzilla

### ISSUE THREAD

**Issue by vkrizan** [python-bugzilla/python-bugzilla#129]
Hi,

Forcing change of class in `_init_class_from_url` for when Red Hat bugzilla is used.

```
class MyBugzilla(RHBugzilla):  # or inheritance from Bugzilla class and url set to rhbz
    def my_method(self):
        pass
```

when used
```
AttributeError: 'RHBugzilla' object has no attribute 'my_method'
```

Is it necessary to change the class? Can it set variables and append necessary methods instead?

Thank you.

**Comment by crobinso** [comment]
It's not functionally necessary but it's the way the API has always worked, so changing it could be a semantic API break for users. Maybe we can make the override smarter by only changing it if the starting class is plain Bugzilla(). Can you make a change like that to python-bugzilla and see if it fixes your usecase?

**Comment by vkrizan** [comment]
How about changing the [isinstance and issubclass hooks](https://docs.python.org/3/reference/datamodel.html#customizing-instance-and-subclass-checks) and drop the class mangling? The methods can be either dynamically added to main `Bugzilla`  instance or they can be included on the main class (with a check).

We've fixed our application by overriding `_init_class_from_url` to a noop.

**Comment by crobinso** [comment]
Thanks for the suggestion. Since that would still be a semantic change, I went with my suggested change. I added tests to ensure we won't overwrite __class__ if the starting class isn't Bugzilla. I made a note to drop that __class__ override behavior in a future release

**Comment by vkrizan** [comment]
Thank you.
