### ISSUE TITLE
KeyError when querying bug data from Bugzilla version 3.x

### ISSUE THREAD

**Issue by mprpic** [python-bugzilla/python-bugzilla#13]
I'm trying to get bug information from several Bugzilla instances, namely:

    In [12]: for url in urls:
       ....:        bz = Bugzilla(url)
       ....:        print(url, bz.bz_ver_major, bz.bz_ver_minor)
       ....: 
    ('https://bugzilla.novell.com', 3, 4)
    ('https://bugs.gentoo.org', 3, 0)
    ('https://bugs.mageia.org', 4, 4)
    ('https://bugzilla.redhat.com', 4, 4)

When trying `bz.getbug(123)` on Novell's and Gentoo's Bugzilla instance, I hit the else branch of [this](https://github.com/python-bugzilla/python-bugzilla/blob/0b2397db551b8969fa7b71a15cf2ff80d3146437/bugzilla/base.py#L1032) check that tries to access `b['internals']`. This attribute does not exist in the bug dictionary so it fails with a `KeyError: 'internals'` traceback.

If I remove that check for the BZ version altogether, all seems to work just fine. Was the `internals` used at some point and has been removed now? I'd submit a patch removing that check but would like to see first if it's actually used for anything. I can't seem to find any `internals` attribute exposed by any Bugzilla instances.

Thanks!

**Comment by crobinso** [comment]
thanks for the report. 'internals' was exposed by bugzilla < 4 instances. the problem here is that our version 'detection' is really screwy and uses hardcoded values. see bugzilla/__init__.py . so it's catching incorrect values for bugzilla.novell.com (which we have hardcoded to 3.4) and bugs.gentoo.org (which is version 5.0 but we fail to detect that so fall back to 3.0).

that whole stuff needs a larger rework but if you want to take a stab at fixing those two bits, even just continuing the current crappy scheme, would be much appreciated

**Comment by mprpic** [comment]
Thanks for the quirk reply!

Fixing the hardcoded version is easy enough for Novell, they seem to be using 4.4.11:

https://bugzilla.novell.com/page.cgi?id=release-notes.html

Gentoo however uses 5.0.2 and since there is no Bugzilla50 class I'm hesitant reusing some older version class as that may have unexpected side effects. Do you happen to know what changed between 4.4 to 5.0 in upstream that could potentially be coded in a new Bugzilla50 class which would just inherit from 44, similarly as 44 inherits from 36?

**Comment by crobinso** [comment]
No I haven't looked at the bugzilla 5.0 API changes yet. Maybe just detect version 5 and use the latest bugzilla class we have? That will likely work for at least some of the APIs and is probably the best we can do until someone digs deeper

**Comment by mprpic** [comment]
Fair enough, PR coming in soon! :-)

**Comment by diaojunxian** [comment]
@crobinso  I had installed python-bugzilla version == 1.2.2,but I also got the error:
```
Traceback (most recent call last):
  File "/Users/djx/Documents/ci_ios/app/bugzilla-data.py", line 30, in <module>
    bug = bz.getbug(16298)
  File "/Library/Python/2.7/site-packages/bugzilla/base.py", line 1030, in getbug
    exclude_fields=exclude_fields, extra_fields=extra_fields)
  File "/Library/Python/2.7/site-packages/bugzilla/base.py", line 1023, in _getbug
    extra_fields=extra_fields)[0]
  File "/Library/Python/2.7/site-packages/bugzilla/base.py", line 1000, in _getbugs
    bugdict = dict([(b['id'], b['internals']) for b in r['bugs']])
KeyError: 'internals'
```
My code is:
```
import bugzilla

bz = bugzilla.Bugzilla(url='xxxxx/xmlrpc.cgi')
bz.login('xx', 'xxx')

bug = bz.getbug(22263)

print("Fetched bug #%s:" % bug.id)
print("  Product   = %s" % bug.product)
print("  Component = %s" % bug.component)
print("  Status    = %s" % bug.status)
print("  Resolution= %s" % bug.resolution)
print("  Summary   = %s" % bug.summary)
```

**Comment by crobinso** [comment]
@diaojunxian you'll probably want to try the github version, a new release hasn't come out yet
