### ISSUE TITLE
Timeout on requests

### ISSUE THREAD

**Issue by pypingou** [python-bugzilla/python-bugzilla#131]
If I am not mistaking, it looks like python-bugzilla is not setting any timeout to the requests it makes using the ``requests`` library. This is considered bad practices as it can lead to programs being forever stuck waiting on a request to end.

Upstream doc: https://requests.readthedocs.io/en/master/user/quickstart/#timeouts
Relevant quote:
``Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely``

In toddlers, we have found a way to define a default timeout, unless one is provided (be that an actual timeout value or a ``None`` for infinite waiting), this may inspire you: https://pagure.io/fedora-infra/toddlers/blob/master/f/toddlers/utils/requests.py (just checked, both programs are under the same license)

**Comment by pypingou** [comment]
Note: I looked at this file: https://github.com/python-bugzilla/python-bugzilla/blob/master/bugzilla/_session.py and how it is used/called in https://github.com/python-bugzilla/python-bugzilla/blob/a3893e636b9c589a84489631c499607749ac6882/bugzilla/_backendrest.py#L50-L61 or https://github.com/python-bugzilla/python-bugzilla/blob/a3893e636b9c589a84489631c499607749ac6882/bugzilla/_backendxmlrpc.py#L44

**Comment by crobinso** [comment]
Thanks for the report. The `toddlers` idea is nice but give that there's only the 4 instances internally we care about, we could move get/put/post wrappers into _BugzillaSession and set a timeout there.

Choosing a timeout is less clear though. Some calls can take a long time to complete. bugzilla has its timeout which for rhbz is 60 or 120 seconds if I recall, but presumably this is configurable on the bugzilla side. Maybe using something like 5 minutes is safe for general purpose

**Comment by pypingou** [comment]
> Maybe using something like 5 minutes is safe for general purpose
:+1: 

We could also potentially override it with an environment variable?
Something like:

````
timeout = os.environ.get('BUGZILLA_TIMEOUT') or 5*60
````

**Comment by crobinso** [comment]
I added a default timeout of 5 minutes, and a PYTHONBUGZILLA_REQUESTS_TIMEOUT variable to override it

**Comment by pypingou** [comment]
On Sat, Oct 03, 2020 at 12:26:07PM -0700, Cole Robinson wrote:
>    I added a default timeout of 5 minutes, and a
>    PYTHONBUGZILLA_REQUESTS_TIMEOUT variable to override it

Sweet, thanks! :)
