### ISSUE TITLE
`query()` injects Bugzilla_api_key into query dict passed as argument

### ISSUE THREAD

**Issue by vashirov** [python-bugzilla/python-bugzilla#132]
I'm using the following code:
```
import os
import bugzilla

BZ_URL = "https://bugzilla.redhat.com"

with open(os.path.expanduser('~/.bzapikey')) as keyfile:
    api_key = keyfile.readline()
bzapi = bugzilla.Bugzilla(BZ_URL, api_key=api_key)
assert bzapi.logged_in

bz_query = {'f1': 'bug_id', 'o1': 'equals', 'v1': '1'}
bzapi.query(bz_query)
print(bz_query)
```

```
$ python test_bz.py
{'f1': 'bug_id', 'o1': 'equals', 'v1': '1', 'Bugzilla_api_key': 'REDACTED\n'}
```
I did not expect that after running `query()` it will modify my `bz_query` argument and inject `Bugzilla_api_key` into it. I reused `bz_query` for constructing urls and accidentally leaked my API key.

The obvious workaround is to pass `bz_query.copy()`, but I was wondering if it is a bug or a design choice?
Thanks.

**Comment by crobinso** [comment]
Hmm yeah that's not good. Thanks for the report. We should fix this on python-bugzilla side
