### ISSUE TITLE
[Missing Capability] Set needinfo on assignee, or email

### ISSUE THREAD

**Issue by sferich888** [python-bugzilla/python-bugzilla#133]
We have the ability to ask for additional information on a bug: `bugzilla modify BZ_ID -f needinfo? --comment "why I need more information" [--private]` but we don't seem to have the ability to direct this request at a user (email) or the 'assignee' of the bug.

Is this missing functionality (an thus something we need to address as a new feature), or is this user error  or lacking documentation  on how to run such a request?

**Comment by crobinso** [comment]
Because of the reasons I mentioned above I don't think this is a good fit for python-bugzilla
