### ISSUE TITLE
RFE: Ability to query number of comments / last_comment_id directly?

### ISSUE THREAD

**Issue by frantisekz** [python-bugzilla/python-bugzilla#138]
In oraculum [0], we're processing literally tens of thousands of bugs every hour, so we'd like to optimize querying bugzilla and reduce memory consumption as much as possible.

One area of optimization would be to stop querying all the comments for bugs. However, we need the total number of bug comments. Would it be possible to add an option to have something like:

```
query["include_fields"] = ['blocks', 'comment_count' or 'last_comment_id',...]
"comments": (comment_count - 1)
```

instead of : 

```
query["include_fields"] = ['blocks', 'comments',...]
"comments": (len(bug.comments) - 1)
```

?

Thanks!

[0] https://pagure.io/fedora-qa/oraculum

**Comment by crobinso** [comment]
Hmm, passing include_fields=["comments.id"] should in theory limit the return 'comments' data to only the id field, but that doesn't seem to work with bugzilla.redhat.com which is probably a bug.

Can you explain more what your tool is doing? Are you requerying all the data about a list of bugs periodically?
If you are trying to use comment count as a way to determine if the bug changed in some meaningful way, there are better ways to do it IMO.

You can you use bugzilla's advanced search UI to have a query return only bugs that have changed in some way after a certain timestamp. Generate a bugzilla search URL like that and pass it to python-bugzilla as described here: https://blog.wikichoon.com/2014/05/invoking-bugzilla-query-url-from.html

If you specifically need to know about comments and no other changes, in the advanced search UI you can do 'Comment  changed after   2020-10-01'  for example

**Comment by frantisekz** [comment]
Yeah, sorry, I could've described it better.

Oraculum is backend for Packager Dashboard: https://packager.fedorainfracloud.org/ ; it uses comments field to just display the number of comments for bugs.

> Hmm, passing include_fields=["comments.id"] should in theory limit the return 'comments' data to only the id field, but that doesn't seem to work with bugzilla.redhat.com which is probably a bug.

Do you think I should go ahead and report it to RH BZ maintainers?

> Are you requerying all the data about a list of bugs periodically?

Yes.

> You can you use bugzilla's advanced search UI to have a query return only bugs that have changed in some way after a certain timestamp. Generate a bugzilla search URL like that and pass it to python-bugzilla as described here: https://blog.wikichoon.com/2014/05/invoking-bugzilla-query-url-from.html

Hmm, thanks for the hint, however, that'd require rewriting some core parts of the app :( , I'll leave it on backlog.

Thanks for the reply!

**Comment by crobinso** [comment]
Yes I think it would be useful to file a bug against bugzilla.redhat.com
