### ISSUE TITLE
Support 'cf_verified' in build_update method

### ISSUE THREAD

**Issue by yanan-fu** [python-bugzilla/python-bugzilla#146]
In some usage, the 'cf_verified' field need be updated automatically, but the `build_update` method does not support this field now,  seems it is a read only filed with python-bugzilla method.

Could we support update 'cf_verified' filed with python-bugzilla ? Thanks a lot!

**Comment by crobinso** [comment]
Thanks for the suggestion. `cf_` means 'custom field`, meaning the bugzilla instance added that for its own usage. We don't plan to add any more custom fields to `build_update`, but you can do it by hand:

```python
update = bz.build_update(...)
update["cf_verified"] = "MYVALUE"
bz.update_bugs(buglist, update)
```

**Comment by yanan-fu** [comment]
@crobinso  Thanks, update the data after build_update is ok for me too, just did not use in that way but use REST API as a workaround before.  Thanks again.
