### ISSUE TITLE
Paginating a query

### ISSUE THREAD

**Issue by hroncok** [python-bugzilla/python-bugzilla#149]
Hello, I've been told via internal RH channels that bugzilla search results will soon be paginated. It seems that I've already been hit by this issue in one of my scripts.

Consider this:

```pycon
>>> import bugzilla
>>> bz = bugzilla.Bugzilla("https://bugzilla.redhat.com")
>>> ftibug = bz.getbug("F35FailsToInstall")
>>> query_fti = bz.build_query(product="Fedora")
>>> query_fti["blocks"] = ftibug.id
>>> results = bz.query(query_fti)
>>> len(results)
1000
>>> type(results)
<class 'list'>
```

I see that actually, the number should be 1130.

How do I paginate via the library?

-----------

EDIT on 2021-09-13 The default limit is now 20, so the above example will give:

```pycon
>>> ...
>>> len(results)
20
```

**Comment by marceloleitner** [comment]
Basead on https://bugzilla.redhat.com/docs/en/html/integrating/api/Bugzilla/WebService/Bug.html?highlight=offset#search

I think you need to add:
query_fti["limit"] = 1000
query_fti["offset"] = 0
and iterate increasing offset by "limit" until a smaller page is read.

Yet, I would love if python-bugzilla could handle this internally.

**Comment by marceloleitner** [comment]
On why "1000", because I read it on some email. Perhaps a smarter logic is to set limit=0 and detect it from the first page.

**Comment by hroncok** [comment]
```python
import bugzilla
bz = bugzilla.Bugzilla("https://bugzilla.redhat.com")
ftibug = bz.getbug("F35FailsToInstall")
query_fti = bz.build_query(product="Fedora")
query_fti["blocks"] = ftibug.id
query_fti["limit"] = 1000
query_fti["offset"] = 0
results = []
while len(partial := bz.query(query_fti)) == 1000:
    results += partial
    print("offset", query_fti["offset"])
results += partial
len(results)
```

**Comment by tyll** [comment]
> ```python
> import bugzilla
> 
> BZ_PAGE_SIZE = 1000
> 
> bz = bugzilla.Bugzilla("https://bugzilla.redhat.com")
> ftibug = bz.getbug("F35FailsToInstall")
> query_fti = bz.build_query(product="Fedora")
> query_fti["blocks"] = ftibug.id
> query_fti["limit"] = BZ_PAGE_SIZE
> query_fti["offset"] = 0
> results = []
> while len(partial := bz.query(query_fti)) == BZ_PAGE_SIZE:
>     results += partial
>     query_fti["offset"] += BZ_PAGE_SIZE
> results += partial
> len(results)
> ```

This algorithm might miss BZs if the result set changes between the different page queries. So for example if your query would also check if BZs are open and someone closes one of the BZs from the first page after you queried the first page and before you query the second page, the BZ that was supposed to be the first on the second page would not be reported.

A better algorithm would be to sort the result set by bug id and update the query to report only BZs with a higher bug id than the highest bug id from the previous query.

**Comment by mattiaverga** [comment]
```
Limit the number of results returned to int records. If the limit is more than zero and higher than the maximum limit set by the administrator, then the maximum limit will be used instead. If you set the limit equal to zero, then all matching results will be returned instead.
```

So, wouldn't setting `limit=0` bypass the default limit and avoid pagination?

**Comment by funnelfiasco** [comment]
> > Limit the number of results returned to int records. If the limit is more than zero and higher than the maximum limit set by the administrator, then the maximum limit will be used instead. **If you set the limit equal to zero, then all matching results will be returned instead**.
> 
> So, wouldn't setting `limit=0` bypass the default limit and avoid pagination?

I don't believe so. The kilobug limit is a server-side restriction, so setting `limit=0` would, I expect, result in an effective limit of 1000.

**Comment by mattiaverga** [comment]
So, this should not lose results when ticket list changes between queries by ordering results by bug_id and fetch following batch by bug_id greater than the last of the previous batch:
```
import bugzilla

BZ_PAGE_SIZE = 1000

def _iterate_query(querydata):
    """Iterate Bugzilla query until all results are fetched."""
    results = bz.query(querydata)
    if len(results) == BZ_PAGE_SIZE:
        last_result_id = results[-1].id
        querydata['f1'] = 'bug_id'
        querydata['o1'] = 'greaterthan'
        querydata['v1'] = last_result_id
        results += _iterate_query(querydata)
    return results

bz = bugzilla.Bugzilla("https://bugzilla.redhat.com")
ftibug = bz.getbug("F35FailsToInstall")
query_fti = bz.build_query(product="Fedora")
query_fti["blocks"] = ftibug.id
query_fti["limit"] = BZ_PAGE_SIZE
query_fti["offset"] = 0
query_fti["order"] = "bug_id"
results = []
results = _iterate_query(query_fti)
len(results)
```
(not sure if the example actually works, I've modified what I used in review-stats to match the previous example query, but the logic is the same)

**Comment by joepvd** [comment]
This is worthwhile to track in the context of pagination limits for some use cases: https://bugzilla.redhat.com/show_bug.cgi?id=2005153

**Comment by kkaarreell** [comment]
Hi @mattiaverga , I have tried `query_fti["order"] = "bug_id"` but it didn't work. Did you test it?

**Comment by mattiaverga** [comment]
> Hi @mattiaverga , I have tried `query_fti["order"] = "bug_id"` but it didn't work. Did you test it?

Yes, I tried it and it used to work. But it seems that now setting limit > 20 doesn't work anymore for unauthenticated users. I've published a [gist](https://gist.github.com/mattiaverga/7ec1aef6d23311320a1634c1c5ac53f7) where I refined the code and I've tested just now.

**Comment by kkaarreell** [comment]
> > Hi @mattiaverga , I have tried `query_fti["order"] = "bug_id"` but it didn't work. Did you test it?
> 
> Yes, I tried it and it used to work.

It didn't work for me, results were not sorted. But in the proposed patch above I can see `query["order_by"]` instead of `query["order"]` so I guess this is the culprit.

**Comment by crobinso** [comment]
Hi all, sorry for lack of response, I was on paternity leave from Aug 1st until last week, so I'm catching up on this.

I think @jirkade's code at https://github.com/python-bugzilla/python-bugzilla/issues/149#issuecomment-929966694 is the state of the art so far, though it doesn't apply directly to python-bugzilla usage. Thanks Jirka!

The key pieces are:
* `query["limit"] = 0` to request bugzilla's server side limit. Hardcoding 1000 is asking for pain if bugzilla admins ever have to lower that number
* `query["order_on"] = "bug_id"`, to ensure results are returned ordered by bug `id`
* Returned query data has a `total_matches` numeric field which reports how many results there would be if there was no limit, so use that to determine if you should keep on querying
* Splicing in the `fX` `vX` and `oX` query format magic to limit the query to only bugs with an ID higher than the last fetched bug. This makes sure you don't miss a bug across query calls

That's only going to work for certain premade queries though, see the `j_top` validation bit. Trying to implement this transparently for any pre-existing query is not an option IMO.

I'm not entirely sure what to do on the python-bugzilla side TBH. On internal Red Hat bugzilla lists there's more changes being discussed in this area, so I'm going to wait and see what else lands

**Comment by crobinso** [comment]
Also if you are using `/usr/bin/bugzilla query`, you can pass `--field=limit=0` to raise the query up to 1000 results. If you need more than that, for now you'll need to wire up your own logic to call `/usr/bin/bugzilla query` multiple times

**Comment by cmyster** [comment]
Hi,
When querying for _something_ and it finds more than 20 matches, the limit=0 seems to work, but not if it is a query from URL that uses quick search.
For instance, this list of bugs will only return the first 20:
https://bugzilla.redhat.com/buglist.cgi?quicksearch=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C15%2C16%2C17%2C18%2C19%2C20%2C21

Is there a way to apply the same logic of limit=0 to this sort of query from URL as well?

**Comment by kkaarreell** [comment]
Hi @cmyster, simply add. `&limit=0` to the URL.

**Comment by ktdreyer** [comment]
Here's where I've added pagination to our tooling for Ceph https://github.com/ktdreyer/rhcephbugs/commit/0afe2a37466a199e0981cfa15f083a4cb8642516

**Comment by kpfleming** [comment]
I've just opened #173 which would make this easier for users of the RH Bugzilla, since it has an extension which reports the total number of matches for a query (whether it was limited or not). Usage would be similar to this:
```python
... build query ...
results = []
query["limit"] = 1000 # note the limit has to be set otherwise the default of 20 is used
query["order"] = "bug_id"
_results = bz.query(query)
while len(_results) < _results.total_matches:
  results.extend(_results)
  query["f1"] = "bug_id"
  query["o1"] = "greaterthan"
  query["v1"] = _results[-1].id
  _results = bzapi.query(query)
results.extend(_results)
```

**Comment by crobinso** [comment]
Nothing ever landed in python-bugzilla git for this. But I just sent two PRs that kinda help:

- This one adds `query_return_extra()` function which returns `(buglist, values)`, where values is the extra query info like `limit`, `offset`, `total_matches` that rhbz returns: https://github.com/python-bugzilla/python-bugzilla/pull/207  . So that's an official API way to get access to that data if you want it.

- This PR adds `examples/redhat_query_all.py` which instead uses the rhbz extension query option `ids_only=True` which bypasses the query limit but only returns bug ids, which we then paginate manually with a getbugs call. This saves having to deal with limit, offset, and total_matches at all, or do any of the advanced query hacking mentioned above.

I don't plan on adding any rhbz specific `query_all` API to the library, since enshrining rhbz specific behavior into the API has always been pain in the long term.

**Comment by crobinso** [comment]
The PRs mentioned above have landed. I think that's all we are going to do here, so I'm closing this
