### ISSUE TITLE
Cannot create a search query with custom cf_ fields

### ISSUE THREAD

**Issue by Dark-Passenger** [python-bugzilla/python-bugzilla#15]
Hi,
Sorry if this has been something covered before but there is no documentation for python bugzilla that i could find. 

I am building a search query using bugs = bz.query(bz.build_query(cf_fixversion=value))

This is a custom field that works when searched with the UI but gives a keyword error when using the module. I have a local installation of buzilla 4.4

**Comment by crobinso** [comment]
build_query is just meant to be a helper function for building a query dict. so you can do

query = build_query(...)
query["cf_fixversion"] = value
bz.query(query)

**Comment by Dark-Passenger** [comment]
Oh man thanks.

Can you point me to a wiki for Python bugzilla ? The Fedora page is no more(atleast for me)

**Comment by crobinso** [comment]
We don't have one yet. It's on my todo list to clean up the API docs, get them published, put the man page online, etc, a wiki may be part of that
