### ISSUE TITLE
python-bugzilla examples could not be used for gcc.gnu.org/bugzilla

### ISSUE THREAD

**Issue by kw108** [python-bugzilla/python-bugzilla#152]
Hello! I am running the getbug.py to get bug information from gcc.gnu.org/bugzilla. However, when I am revoking getbug()
`
URL = "gcc.gnu.org/bugzilla"
`
`
bzapi = bugzilla.Bugzilla(URL, use_creds=False)
`
`
bug = bzapi.getbug(103621)
`
an error was raised saying
`
bugzilla.exceptions.BugzillaError: mismatched tag: line 70, column 4
`
`
The URL may not be an XMLRPC URL: https://gcc.gnu.org/bugzilla
`
Can anyone give me some hints? Thank you!

**Comment by crobinso** [comment]
Thanks for the report. You need to use 'https://gcc.gnu.org/bugzilla/xmlrpc.cgi' . We attempt to append an xmlrpc.cgi path if the URL doesn't already have a path in it, so the heuristic wasn't triggering here
