### ISSUE TITLE
429 Client Error: Too Many Requests for url: https://bugzilla.mozilla.org/xmlrpc.cgi

### ISSUE THREAD

**Issue by heihun123** [python-bugzilla/python-bugzilla#154]
When I get bugs from bugzilla.mozilla.org by python-bugzilla package, but I cannot get too many bugs in a short time. As shown in the figure, if too many bug reports are obtained in a short period of time, the error will happen,
```
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://bugzilla.mozilla.org/xmlrpc.cgi. 
```
I had to sleep my program to solve this problem, but this greatly increased the time required to get bugs. I want to know if there are other ways to solve this problem in the python-bugzilla package.

![image](https://user-images.githubusercontent.com/35858136/147626273-1e565170-aa89-42df-9719-a9d18c38cfae.png)

**Comment by crobinso** [comment]
Thanks for the report. I think this is on mozilla.org side. I believe bugzilla.mozilla.org is phasing out xmlrpc. Try using https://bugzilla.mozilla.org/rest and see if it makes any difference
