### ISSUE TITLE
How to get the comment changing history?

### ISSUE THREAD

**Issue by SuYanqi** [python-bugzilla/python-bugzilla#166]
Hi,

I found that comments on Mozilla Bugzilla can be changed and the changing history has been recorded.
For example, comment 1 of this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1673164.

Where they are saved and how can I get them?

Thanks

**Comment by crobinso** [comment]
So on bugzilla.redhat.com where I have access, comment #0 is editable. When edited, there's a change listed at the bottom of the web UI, but it doesn't track what text changed. If you use `bug.comments` in python bugzilla code, it only shows the latest updated text. If you use `bug.get_history_raw()` I do see a change notification like this:

```
                       {'changes': [{'added': 'updated',
                                     'field_name': 'longdesc',
                                     'removed': '0'}],
                        'when': <DateTime '20240205T19:58:26' at 0x7f7d78237b90>,
                        'who': 'crobinso@redhat.com'}],
```

But notice it doesn't show the updated text.

If you have API access to bugzilla.mozilla.org, see if the `get_history_raw()` command returns the changed text. But that's the best guess I have. If it's not in the bugzilla instance API there's nothing we can do on python-bugzilla side.
