### ISSUE TITLE
Python-bugzilla doesn't support field-array option

### ISSUE THREAD

**Issue by ljavorsk** [python-bugzilla/python-bugzilla#167]
I was trying to set a Verified:Tested value into multiple Bugzillas, however, the current python-bugzilla-cli doesn't support such action.

The problem is that `cf_verified` field is the type of array, which cannot be changed using the `bugzilla modify --field=cf_verified=Tested`

The pre-verification is nowadays a "must-have" thing to have in Bugzillas and it would be beneficial if we could add it using the python-bugzilla tool.

**Comment by crobinso** [comment]
Sorry for the late response. The request makes sense. we probably need a designated `--field-array`, or maybe something really generic like `--field-json`  which requires passing in full valid json that specifies both the variable name and the value we are setting.

**Comment by crobinso** [comment]
Actually there was another bug already tracking this, with more detail, let's use that one: https://github.com/python-bugzilla/python-bugzilla/issues/163
