### ISSUE TITLE
RFE: bugzilla attach `--field` option

### ISSUE THREAD

**Issue by derekschrock** [python-bugzilla/python-bugzilla#169]
[FreeBSD bugzilla](https://bugs.freebsd.org) has flags for attachments.

Is it possible to have `bugzilla attach` have the `--field FEILD` option like `new` `modify` `query`?

**Comment by crobinso** [comment]
Sorry for late response. Sounds like that would make sense to add.

What fields need to be set?
Can you come up with an example API call that does what you want? If so it will be easier to figure out how to wire up and test for the command line

**Comment by derekschrock** [comment]
I don't but I can start to look if I can find a sandbox bugzilla to play with.

However, the fields (at least from bugs.freebsd.org's Bugzilla) would be file, description, content type, and flags.  I'd assume flags would be maybe be custom per-instance so a user provided flag key and value.

![Screenshot 2024-02-05 at 6 59 05 PM](https://github.com/python-bugzilla/python-bugzilla/assets/1100398/a813091c-66b8-480d-b5d9-1b7922712ede)

**Comment by linimon** [comment]
> I don't but I can start to look if I can find a sandbox bugzilla to play with.
> 
> However, the fields (at least from bugs.freebsd.org's Bugzilla) would be file, description, content type, and flags. I'd assume flags would be maybe be custom per-instance so a user provided flag key and value.
> 
> ![Screenshot 2024-02-05 at 6 59 05 PM](https://private-user-images.githubusercontent.com/1100398/302460356-a813091c-66b8-480d-b5d9-1b7922712ede.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzg4NjAsIm5iZiI6MTcwNzMzODU2MCwicGF0aCI6Ii8xMTAwMzk4LzMwMjQ2MDM1Ni1hODEzMDkxYy02NmI4LTQ4MGQtYjVkOS0xYjc5MjI3MTJlZGUuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMjA0MjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU4NTlhN2YxNTE2ZjJiZjVhM2RiN2NiN2IwNDNkMDgwYmJlNmU4OTAyNDE1ZDY0NDVmNWJlYjIwZDhmZTNmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ruHQYmo4nKT54lK6Z8B96SNPyDkY_qWXnJfvUP8y6yE)

FreeBSD bugzilla flags are heavily modified both to describe what to do with the attachment as well as other things, yes.  (We've kind of overloaded the semantics.)

**Comment by derekschrock** [comment]
I can confirm this is working with `--field is_patch=yes` and `--field-json ...` attachment flags.
