### ISSUE TITLE
Can you provide some basic documentation for the python scripting api?

### ISSUE THREAD

**Issue by MalloZup** [python-bugzilla/python-bugzilla#17]
Hi All,

i found this project really interesting, but i see no basic documentation, like access bugzilla with python script.
Which methods should be used and so on... etc! 

Thx you in advance for the good work :)

**Comment by crobinso** [comment]
yup, it's on my todo list

**Comment by MalloZup** [comment]
@crobinso  ok thx, can you give me a dead-line for the documentation? :)

**Comment by crobinso** [comment]
I'll be pushing some example scripts before the end of the week which will probably cover your needs. Fully hosted API docs may take a while though

**Comment by MalloZup** [comment]
@crobinso  Ok cool yes, some samples will be nice +1
