### ISSUE TITLE
Pylint integration

### ISSUE THREAD

**Issue by crazyscientist** [python-bugzilla/python-bugzilla#185]
* [ ] Please add a pylint-job to the Github actions.
* [ ] Increase the line limit (to 100 chars?).

**Comment by crazyscientist** [comment]
I have to admit that I have little to no experience with `black` or `flake8`.

For the last 5 years, we (at work) have been using `pylint` (latest version from PyPI) in the CI. Depending on the project, it's configured to be more or less strict.

Now that you mention it, I remember the occasional hiccup due to a regression, changed check or new check. Your proposal to pin the pylint version and turn its config into a curated allowlist sounds like a sane approach.

Should I refactor my PR for this right away?

---

I suppose, we can use both: `black` for auto-formatting in the pre-commit and `pylint` for linting in the CI :thinking:.

**Comment by crobinso** [comment]
Coming back to this.

I think if the PR pins to a specific pylint version, that's good enough for a start. Will make CI predictable for contributors at least.

Then when we, using newer distro or pip provided pylint, notice that new pylint errors are popping up on our local machines, we submit a PR to bump the pylint version, and fix or exclude the new errors. That seems like a sane way to handle it.

`black` or other tool usage can come later / be separate.

Sound good?

**Comment by crazyscientist** [comment]
> if the PR pins to a specific pylint version

I'm not in the habit of version pinning and rarely noticed issues due to pylint version updates. But that could be an experience that might not apply to this project.

Would it be OK for you to only pin the minor version (`pylint < 3.1`) or would you prefer pinning of the exact version (`pylint == 3.0.3`)?

> `black` or other tool usage can come later / be separate.
>
> Sound good?

Absolutely. :+1:

**Comment by crobinso** [comment]
@crazyscientist Let's try the looser version matching (ex `pylint < 3.1`) and see how that goes
