### ISSUE TITLE
Fetching component details does not work in Bugzilla 5.0

### ISSUE THREAD

**Issue by janhollevoet** [python-bugzilla/python-bugzilla#19]
When requesting the component details in Bugzilla 5.0, the following error comes:

RuntimeError: This bugzilla version does not support fetching component details.

The related code is:

def _getcomponentsdetails(self, product):
        # Originally this was a RH extension getProdCompDetails
        # Upstream support has been available since 4.2
        if not self._check_version(4, 2):
            raise RuntimeError("This bugzilla version does not support "
                               "fetching component details.")

However, when omitting this check, the function seems to be supported.

**Comment by crobinso** [comment]
Are you testing against a public bugzilla instance I can access? Most of my testing is against bugzilla.redhat.com, which isn't on 5.0 yet

**Comment by janhollevoet** [comment]
No, not public. It's a local 5.0.3 instance of Bugzilla.

**Comment by crobinso** [comment]
Okay, I'll keep this open then. I think partner-bugzilla.redhat.com should be updated to bugzilla 5 relatively soon. Thanks for the report!

**Comment by janhollevoet** [comment]
Thanks for the module and the work :-)

**Comment by kwizart** [comment]
bugzilla.rpmfusion.org is a public bugzilla 5.0 instance, we might have this bug.
That been said,
BZ=bugzilla.Bugzilla(url='https://bugzilla.rpmfusion.org/xmlrpc.cgi')
BZ.__class__
Out[4]: bugzilla.bugzilla3.Bugzilla3
So this lead to another issue where the right class isn't found (forcing the use of bugzilla44 works better for us).

**Comment by crobinso** [comment]
@kwizart can you try with latest git?

**Comment by crobinso** [comment]
I pushed a commit dropping the version check for getcomponentsdetails. I suspect the root issue is the same by @kwizart, that python-bugzilla wasn't detecting the version correctly. This was fixed upstream a while ago. Just trying to wrap up a few more issues before pushing a release.
