### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by gsal** [python-bugzilla/python-bugzilla#209]
Hi, trying to use the bugzilla command line program and having a hard time; could use some help. 

Error: `json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)`

I did create a ~/.config/python-bugzilla/bugzillarc file with my api key in it; not sure if it is being used. 

How can I test whether I am able to authenticate, in the first place?

**Comment by crobinso** [comment]
Thanks for the report. Please provide the `--debug` flag and provide the full output, along with the full command line you are running

**Comment by gsal** [comment]
Never mind. 

After spending the evening trying this and that and even trying another program (bugsy) without success, I decided to write to one of the IT guys, just to learn that they had disabled something about a year ago to carry some test and they forgot to re-instate it...after that, this program started to work just fine.

Thanks for checking up on me.
