### ISSUE TITLE
using python-bugzilla on bugs.eclipse.org

### ISSUE THREAD

**Issue by valeriocos** [python-bugzilla/python-bugzilla#21]
Hi,
I'm trying to use python-bugzilla to access https://bugs.eclipse.org/bugs/, but I'm getting some errors.
Is it possible to use it? If so, could you point me out some documentation/examples

```
import bugzilla

def main():
    bz = bugzilla.Bugzilla(url='https://bugs.eclipse.org/bugs/')

if __name__ == "__main__":
    main()
```

**Comment by crobinso** [comment]
In this case our URL fixup code doesn't work, you'll need to specify the exact xmlrpc API. https://bugs.eclipse.org/bugs/xmlrpc.cgi

**Comment by LeoUfimtsev** [comment]
This really helped me. Thank you.

If of use:

Bash:

	alias bugzilla-eclipse="bugzilla --bugzilla=https://bugs.eclipse.org/bugs/xmlrpc.cgi"
	bugzilla-eclipse query --bug_id 500196
	bugzilla-eclipse query --bug_id 500196 --raw    # << see all attribute fields.
	bugzilla-eclipse query -w followup   #whiteboard = followup

Python:

    import bugzilla

    URL = "https://bugs.eclipse.org/bugs/xmlrpc.cgi"
    bzapi = bugzilla.Bugzilla(URL)

    if __name__ == '__main__':
        query = bzapi.build_query(status_whiteboard="followup")  # See build_query() docu for fields.
        bugs = bzapi.query(query)
        
        for bug in bugs :
            print(bug.getwhiteboard())   #bug.get* can be many things, ex id, status etc.. see bug api.
