### ISSUE TITLE
Are there any plans to introduce a release after 3.2.0 ?

### ISSUE THREAD

**Issue by osoukup** [python-bugzilla/python-bugzilla#211]
Hello,

I recently found out that the unreadable error messages 3.2.0 produces when using with the REST API can be made easily readable by just updating to

https://github.com/python-bugzilla/python-bugzilla/commit/138caf8aa72757329aa92c1acc66b4302486ac35

or above. There is no released version containing this change yet so I am just pinning the most recent commit. Out of curiosity are there any plans to release a version containing this nice change?

Regards
Ondřej

**Comment by crazyscientist** [comment]
Hi @osoukup,

OMG, we definitely should draft a new release. IIRC, there are a couple of really nice bugfixes available...

**Comment by crazyscientist** [comment]
v3.3.0 was released :partying_face:
