### ISSUE TITLE
How to order query results by date created

### ISSUE THREAD

**Issue by gbnk0** [python-bugzilla/python-bugzilla#214]
Hi,
I'm trying to order the query results by creation time for getting the last X bugs.
I tried to pass 
```order="opendate DESC"```

But without success

Regards

**Comment by gbnk0** [comment]
It's OK.
```
    query = bzapi.build_query(
        product=product, limit=1)
    query["order"] = "opendate DESC"
```

Regards

**Comment by crazyscientist** [comment]
> It's OK.

@gbnk0 Thanks for the positive feedback. I'll close the issue then.
