### ISSUE TITLE
How can I update a custom cf_ field?

### ISSUE THREAD

**Issue by AviSub** [python-bugzilla/python-bugzilla#22]
Is build_update will work?
If so , do you have an example of the syntax?

Thank you

**Comment by crobinso** [comment]
You basically need to do:

update = bzapi.build_update(...)
update["cf_my_field"] = "foo"
bugs = bz.update(update)

build_update() just returns a python dict()

**Comment by AviSub** [comment]
Works great !! Thanks

**Comment by scm20008** [comment]
now the codes are changed. how can I update the customized bug now? @crobinso 

Could you please help me with my problem? thanks.

and the following is my code:
`bug = bz.getbug(bug_id)
update = bz.build_update(cf_git_tag="%s" % git_tag)
bz.update_bugs([bug.id], update)
bug.refresh()`

after I run the code, I get the following error:
build_update() got an unexpected keyword argument 'cf_git_tag'

**Comment by AviSub** [comment]
I suggest to try update = bz.build_update [‘cf_git_tag’] = ‘git_tag’

Thanks,
Avi

**Comment by crobinso** [comment]
You need to follow the same pattern I mentioned in the comment up above https://github.com/python-bugzilla/python-bugzilla/issues/22#issuecomment-241849820

**Comment by scm20008** [comment]
@AviSub @crobinso thank you all very much for your support!
I have fixed the problem by myself.
