### ISSUE TITLE
Use a CHANGELOG or HISTORY file

### ISSUE THREAD

**Issue by rochacbruno** [python-bugzilla/python-bugzilla#31]
HI!

At Red Hat SatelliteQE we are using this library, and also using PyUp which sends PRs like this:

https://github.com/SatelliteQE/robottelo/pull/4308 

That is very nice but we miss the changelog/history in the PR message.

Can you add a a HISTORY/CHANGELOG file listing the release notes?
(not sure but I guess pyUP also looks to github tags/releases)

**Comment by crobinso** [comment]
Thanks for the report, I just pushed a commit with a NEWS.md file
