### ISSUE TITLE
_init_class_from_url breaks inheritance

### ISSUE THREAD

**Issue by mhlavink** [python-bugzilla/python-bugzilla#34]
base.py: Bugzilla._init_class_from_url breaks inheritance as it's overwrites self.__class__ value to RHBugzilla in some cases. This breaks our code, because this happens even if it is already RHBugzilla or the class is inherited from RHBugzilla.

Fix for this would be to add check if self is already instance if RHBugzilla and early return if so

[fix.patch.txt](https://github.com/python-bugzilla/python-bugzilla/files/932698/fix.patch.txt)

**Comment by crobinso** [comment]
Thanks, your fix looks good, I'll push with proper attribution
