### ISSUE TITLE
bug in bugzilla/base.py

### ISSUE THREAD

**Issue by YuanruiZJU** [python-bugzilla/python-bugzilla#35]
When I use this tool to crawl bug reports from mozilla, an error appears when I use the API getbugs([201-300]). The error is shown as following text:
`TypeError: 'in <string>' requires string as left operand, not int`

It appears when there is some bug whose 'alias' field is a String and some bug id does not exist.
The bug localization seems at bugzilla/base.py line 999.

**Comment by crobinso** [comment]
Thanks for the report, that's a bug due to usually testing with RH bugzilla which always returns alias as a list. I'll fix shortly

**Comment by YuanruiZJU** [comment]
Thanks for your reply! @crobinso
