### ISSUE TITLE
Add python-bugzilla-admin to PyPI maintainer role

### ISSUE THREAD

**Issue by abn** [python-bugzilla/python-bugzilla#51]
In order for build and upload to PyPI from travis to work as expected we need to add the `python-bugzilla-admin` user to the [maintainer role](https://pypi.python.org/pypi?:action=role_form&package_name=python-bugzilla).

**Comment by crobinso** [comment]
What's your username on pypi? I'll add you as an owner then you can make whatever changes you need

**Comment by abn** [comment]
@crobinso abn should work. Thanks.

**Comment by crobinso** [comment]
@abn added on pypi now
