### ISSUE TITLE
Is there a way to query bugs with time filter?

### ISSUE THREAD

**Issue by zhangyuting** [python-bugzilla/python-bugzilla#54]
I saw **build_query()** can use many fields to query bugs, however if the case is "I want all bugs this year", looks I have to query all bugs and filter them manually with local logic.

**Comment by crobinso** [comment]
See this feature: http://blog.wikichoon.com/2014/05/invoking-bugzilla-query-url-from.html

But you need bugzilla.redhat.com or a bugzilla >= 5.0 version for it to work. if you are using older bugzilla then you must do the filtering by hand
