### ISSUE TITLE
bugzilla query doesn't work for Flags?

### ISSUE THREAD

**Issue by xhe123** [python-bugzilla/python-bugzilla#55]
I tried to query the bugs which with the `rhel-7.4.0+` flags, but it doesn't work. I found the bug number are the same when with `--field=flags="rhel-7.4.0+"` and without it. e.g
```
$ bugzilla query  --qa_contact=xhe |wc -l
255  
$ bugzilla query  --qa_contact=xhe --field=flags="rhel-7.4.0+" |wc -l
255 
```

**Comment by crobinso** [comment]
--field needs to accept data in the format that the XMLRPC API expects, which for flags is not a string but something more complex.

Use the 'query --flag' option, that will do what you want
