### ISSUE TITLE
travis: update pip install commands to use --user flag

### ISSUE THREAD

**Issue by abn** [python-bugzilla/python-bugzilla#58]
Update pip install commands in builds to use `--user` flag to ensure this works in non python stages (eg: SonarQube)

Refer: https://github.com/travis-ci/travis-ci/issues/8382

**Comment by crobinso** [comment]
pip install --user broke regular travis steps:
$ pip install --user tox
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

I did: pip ... || true and that seemed to fix the sonar step
