### ISSUE TITLE
time based queries?

### ISSUE THREAD

**Issue by ghoroupi** [python-bugzilla/python-bugzilla#60]
Not necessarily an issue, just was wondering how to query on creation_time before/after a date?   In addition to creation_time, need to same capability for Resolved and Verified state changes.   Any help would be appreciated

**Comment by crobinso** [comment]
For complex queries, the best thing to do is generate a URL query and pass that to python-bugzilla. Only works for bugzilla 5 instances though (and current bugzilla.redhat.com). See here for code example, or if using the command line, try 'bugzilla query --from-url'

https://github.com/python-bugzilla/python-bugzilla/blob/master/examples/query.py#L61
http://blog.wikichoon.com/2014/05/invoking-bugzilla-query-url-from.html
