### ISSUE TITLE
ambiguous description for --tags / missing mentioning in the man page

### ISSUE THREAD

**Issue by DirkSchmitt** [python-bugzilla/python-bugzilla#61]
2 minor documentation issues concerning `--tags` 

`man bugzilla`
-----------------
In `man bugzilla` the `--tags` option is not documented.

`bugzilla modify --help`
-----------------------------
>  --tags TAGS           Tags field.

In bugzilla we found several tag fields, e.g. *Personal Tags*, *Comment Tags*.
So this would be less ambiguous to explicitly name it here.

**Comment by crobinso** [comment]
Thanks for the report. Interesting, they renamed the UI field to personal tags in bugzilla 5. I hadn't seen that before.
