### ISSUE TITLE
Feature Request: Support for tagging comments

### ISSUE THREAD

**Issue by DirkSchmitt** [python-bugzilla/python-bugzilla#62]
I'm missing a way to add an comment with associated tag.

Use Case
------------
Some sort of workflow utility using *bugzilla-cli* to attach comments to a bug entry.

To cleanup the the bug report display in the web browser it would be nice to use the comment collapsing features controlled via the *comment tags*.

**Comment by crobinso** [comment]
I added a --comment-tag option for 'create' and 'modify' command line actions. I don't have a bugzilla instance to test it on though since this is bugzilla5 only and beta-bugzilla.redhat.com doesn't seem to have an option for it, so please give it a spin and let me know if there are issues
