### ISSUE TITLE
Feature Request:  `info --components` should respect  „enabled for bugs“ property.

### ISSUE THREAD

**Issue by DirkSchmitt** [python-bugzilla/python-bugzilla#63]
```bugzilla info --components``` returns all components.
In some use cases only the components with the setting *Enabled For Bugs* are interesting.

It would be nice to have a command line argument like `--active-components` to collects these components via the bugzilla-cli utility.

**Comment by crobinso** [comment]
Thanks, I added --active-components like you suggested
