### ISSUE TITLE
Feature Request: enhance output for external trackers

### ISSUE THREAD

**Issue by sferich888** [python-bugzilla/python-bugzilla#65]
Today, if you query for information (from the cli) and use 'external_bug' the data you get back is in the BZ's [array of 1](https://bugzilla.redhat.com/docs/en/html/api/Bugzilla/WebService/Bug.html) format, which gets translated, to a dictionary of sub-elements. 

Because of this, the --outputformats inability to parse/define what (subfields) you see from this, the output is not very usable, or parsable!

Is there a way, [like what we do with CVE/comments](https://github.com/python-bugzilla/python-bugzilla/blob/master/bin/bugzilla#L655-L690) to improve this?

Mainly the (fields): 
- [ ] ext_bz_bug_id
- [ ] ext_status
- [ ] ext_description

**Comment by crobinso** [comment]
Thanks for the report, I think that's reasonable

**Comment by crobinso** [comment]
Here's what I implemented:

$ ./bugzilla-cli query --bug_id 989253 --outputformat="%{external_bugs}"

External bug: http://bugzilla.gnome.org/show_bug.cgi?id=703421
External bug: https://bugs.launchpad.net/bugs/1203576

On RH bugzilla at least nearly all the bugs I saw were missing any filled in values for status or description so I wasn't sure what to do about listing them if it's inconsistent. Hopefully that's sufficient

**Comment by sferich888** [comment]
This is great! 

The fields I was looking for were the following: 

- e["type"]["description"]
- e["type"]["ext_bz_bug_id"] 
- e["type"]["ext_status"]

However, now that I know how you want this implemented (more or less I can submit PR's) to tweak this. 

That said, I can work with what the URL provides.

**Comment by nhr** [comment]
A side effect of this change is that it is no longer possible to get the external_bugs value as a JSON string. As it happens, I have [written a utility](https://github.com/nhr/shiftzilla) that depends upon being able to look at the external_bugs JSON string, as returned by this utility.

Would it be possible for you to add a flag to the query behavior such that I can get the JSON object instead of this pretty-print output?

**Comment by crobinso** [comment]
#72 is a feature request for adding some kind of global JSON output format value to the command line which I think is the way forward here.

**Comment by nhr** [comment]
Thanks for the pointer!
