### ISSUE TITLE
[RFE] Query for needsinfo flag with specific requestee's email

### ISSUE THREAD

**Issue by omaciel** [python-bugzilla/python-bugzilla#71]
I'm trying to execute a query against Red Hat's Bugzilla instance (version: 4.4) equivalent to what is provided by the following URL:

```https://bugzilla.redhat.com/request.cgi?action=queue&requester=&product=&type=needinfo&status=all&requestee=foo@example.com```

**NOTE**: if you substitute `foo@example.com` for a valid Bugzilla email, you should see something similar to the screenshot below:

![screenshot 2018-04-19 08 45 02](https://user-images.githubusercontent.com/53362/38992270-3cfb13ce-43ae-11e8-9d01-f2cabc493f59.png)

So the idea is to be able to query for ```flag contains string 'needsinfo'``` and ```requestee contains string 'foo@example.com'```.

**Comment by omaciel** [comment]
Hi @crobinso I'm using the API currently taking advantage of both `url_to_query` and `build_query` methods. Right now one can do something like [this](https://github.com/SatelliteQE/bugwrangler/blob/master/bugwrangler/queries.py#L35-L40).

As you can see, one can query for a given flag (or multiple ones) but the query usually expects that there is only one value for the flag (usually one of the following: `+`, `-`, or `?`).

The `needsinfo` flag is a special one because beside the standard value mentioned above, it also contains the email of the person you need information from (e.g. `needsinfo? someone@example.com`).

I have tried to pass this [query](https://bugzilla.redhat.com/request.cgi?action=queue&requester=&product=&type=needinfo&status=all&requestee=jcallaha%40redhat.com&component=&group=type&do_union=1) to `url_to_query` but Bugzilla returns an error.

**Comment by crobinso** [comment]
Hmm I see now that your URL is a request.cgi URL and not a query.cgi URL. Indeed the bugzilla API doesn't know how to handle those types or URLs, it expects to be passed a query.cgi or buglist.cgi URL. So you'll need to go to the 'advanced search' web UI and generate a query that fetches the data you want, then pass it to url_to_query and it should work.

For example, this URL will find all bugs that have needinfo requestee=kernel-maint@redhat.com: https://bugzilla.redhat.com/buglist.cgi?f1=requestees.login_name&list_id=8731497&o1=equals&query_format=advanced&v1=kernel-maint%40redhat.com

**Comment by omaciel** [comment]
Hi @crobinso I'd like to start by apologizing for my very late response. I'm not going to try to come up with an excuse and I'm extremely embarrassed for my delay, so please accept my apology. :/

Your URL was extremely useful to me and I was able to fix my problem by using the arguments you provided in the URL. Thank you so much! 

Sincerely,

Og

**Comment by crobinso** [comment]
No worries I didn't think twice about it
