### ISSUE TITLE
[RFE] Consider a json output formater 

### ISSUE THREAD

**Issue by sferich888** [python-bugzilla/python-bugzilla#72]
It would be nice if the objects pulled out of this tool were presented in a json format. This way you could parse them will tools like `jq`

```
$ bugzilla query -b BUG --outputformat="%{external_bugs}" | jq '.'
parse error: Invalid numeric literal at line 1, column 19
```

**Comment by crobinso** [comment]
Since I never responded, just chiming in to say that I agree a general purpose --json output mode would be useful

**Comment by wking** [comment]
This will probably be pretty easy as part of #75.  Not sure if it's worth the trouble to handle separately?

**Comment by crobinso** [comment]
This is upstream now, `/usr/bin/bugzilla` now has a `--json` option that can be used like other output options.
