### ISSUE TITLE
Unable to set tags?

### ISSUE THREAD

**Issue by larsks** [python-bugzilla/python-bugzilla#73]
I am using the `bugzilla` cli from `python3-bugzilla-2.1.0-2.fc27.noarch` on F27. The problem also reproduces with current master (1e766b4).

I can query bug tags...

```
$ bugzilla query --tags mytags
```

But I can't set tags:

```
$ bugzilla new [...] --tags mytags
bugzilla: error: Extra arguments '['--tags', ',utags']'
```

I also tried:

```
$ bugzilla new [...] --field tags=mytags
Server error: <Fault 53: 'tags is not a valid parameter for the Bugzilla::Bug::create function.'>
```

Is there any way to set tags when creating a new bug?

**Comment by crobinso** [comment]
Thanks for the report, but the bugzilla XMLRPC API does not have any way to set tags at bug creation time. You'll need to do a 'new' followed by an 'update' call

https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#create-bug
