### ISSUE TITLE
Consider making an example of reassigning issues when people leave

### ISSUE THREAD

**Issue by AnSem-Ellwood** [python-bugzilla/python-bugzilla#77]
A common problem with Bugzilla is reassigning bugs to new owners when people move on.  I have such a problem right now where 80+ issues are assigned to a leaver.  This is an ideal use of this module to reassign issues to a new owner.  From the documentation it is not clear if this can be done.  An example would be useful here.

**Comment by crobinso** [comment]
The API just needs better documentation in general. I don't want to add targeted examples like this because it's a slippery slope. Basically look at the query.py example and use build_query for assignee=$oldname, then look at the update.py and use build_update for assignee=$newname

**Comment by crobinso** [comment]
Also specifically for this type of thing, it shouldn't be done on the API side because it will spam email. A bugzilla admin should do it, where AFAIK there's more control
