### ISSUE TITLE
RFE Support API Keys when using the cli tool

### ISSUE THREAD

**Issue by pgagne** [python-bugzilla/python-bugzilla#82]
This library seems to have support for using API keys, but they don't seem to be able to be used by the command line client. 

This would be very useful.

**Comment by crobinso** [comment]
Thanks for the report. You can use api_key via a bugzillarc file, like this example

```
$ cat .config/python-bugzilla/bugzillarc
[bugzilla.redhat.com]
api_key=YOUR-API-KEY
```

Is that sufficient for your needs?

**Comment by xhe123** [comment]
Yes, it looks pretty good for API-Key login.
I need this feature as well, looking forward for it as soon as possible.

**Comment by pgagne** [comment]
@crobinso yeah I think for now, I eventually found that buried in the man page somewhere. I was thinking it might also be a useful to specify it some how when using `bugzilla login` . Perhaps something like `bugzilla login --api-key`, then it prompts for the key.

**Comment by crobinso** [comment]
But if you have the API key, I don't think you want to use 'bugzilla login', especially on bugzilla.redhat.com where login tokens seems to expire after a week. Having an --api-key seems strange to me as it means you are storing the human unfriendly key somewhere and copying it into the password prompt, at which point why not store it in a bugzillarc file and skip all the mess.

Do you know any other tools that have an --api-key type option? I can't think of one by my sample size is quite small

**Comment by ktdreyer** [comment]
It would be kind of nice to automatically write an entry in the `bugzillarc` file in the right syntax. Or maybe python-bugzilla could even log in with a username and password and set up a new API key server-side automatically to get new users going quickly.

In the meantime here's an update to the `--help` text at least: https://github.com/python-bugzilla/python-bugzilla/pull/92

**Comment by danilocesar** [comment]
So, I talked a bit with Cole about this.

bugzilla login --ask-key

Then the tool will ask for the key (so it's not provided in the command line itself) the same way to asks for username/password credentials.

Then we don't have to edit the rc file by hand.

**Comment by crobinso** [comment]
We ended up with `bugzilla login --api-key` which will interactively grab the API key and save it into ~/.config/python-bugzilla/bugzillarc for use with subsequent tool usage

**Comment by pgagne** [comment]
Thanks For adding this!

**Comment by crobinso** [comment]
FYI for anyone that cares, the internal API is different in git now. Rather than

`Bugzilla.interactive_login(use_key=True)`

it is now

` Bugzilla.interactive_save_api_key()`

So, its own top level function.
