### ISSUE TITLE
Is logical operations supported by multiple flags in query?

### ISSUE THREAD

**Issue by xhe123** [python-bugzilla/python-bugzilla#84]
Does bugzilla query support multiple flags? for example the following logical operations:  Thank You!
(qa_ack? OR qa_ack+)
(rhel-7.7.0+ AND qa_test_coverage+ ) or (rhel-7.7.0? OR qa_test_coverage?)

**Comment by crobinso** [comment]
For this you will want to use query --from-url, described here: https://blog.wikichoon.com/2014/05/invoking-bugzilla-query-url-from.html
