### ISSUE TITLE
no option similar to ' This is a minor update (do not send email)' in webui

### ISSUE THREAD

**Issue by cz172638** [python-bugzilla/python-bugzilla#87]
i was moving to another 'email provider' and i decided to change email where i figure as assignee/commenter/cc for components i maintain or i'm active.
within one hour i received 1000+ emails and first 'stoners' poped up :sweat:

**Comment by crobinso** [comment]
Yes it'd be nice to support that, but by my reading the public API does not provide a way to suppress email, see the docs for the Bug.update call: https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#update-bug
