### ISSUE TITLE
[RFE] Allow login via kerberos

### ISSUE THREAD

**Issue by pemensik** [python-bugzilla/python-bugzilla#90]
Since bugzilla login validity period is now shorter that before and it seems it is bound to IP address by default, it would be quite nice if password entering could be omitted.

fedpkg supports kerberos and new bugzilla supports it as well. Is there something that prevents login by kerberos? Noone just implemented it? Is there reason why it is not simple copy & paste from fedpkg?

**Comment by crobinso** [comment]
I asked about this from bugzilla.redhat.com devs. There's no specific kerberos awareness in the bugzilla XMLRPC API. Their recommendation was the to use bugzilla API keys if you need longer term login access:

https://blog.wikichoon.com/2019/01/python-bugzilla-bugzilla-50-api-keys.html

Maybe there's a way to make 'bugzilla login' use kerberos automatically if we have an RH login ticket, but it's certainly outside my realm of experience and I'm unlikely to try and figure it out anytime soon. If someone figures out how to make it work then we can evaluate whether it makes sense to include in python-bugzilla

**Comment by crobinso** [comment]
I think even if someone finds a solution to this it's not going to be 'bugzilla' specific so won't be a good fit for python-bugzilla, so I'm closing this. But if anyone figures out the magic on how to make this work, please consider sharing it here so others can find it
