### ISSUE TITLE
Domain part of user's email address is stripped

### ISSUE THREAD

**Issue by olysonek** [python-bugzilla/python-bugzilla#91]
Hi, I noticed today that when interacting with the Red Hat Bugzilla, python-bugzilla no longer returns the full email address in attributes where it is expected:
```
$ cat a.py 
import bugzilla

bz = bugzilla.Bugzilla('https://bugzilla.redhat.com/xmlrpc.cgi')
user = bz.getuser('olysonek@redhat.com')
print(user.email)
bug = bz.getbug(1669294)
print(bug.creator_detail['email'])
print(bug.comments[0]['creator'])
$ python3 a.py
olysonek
olysonek
olysonek
```

I believe all of the above attributes previously contained the full email address (the same probably applies to `bug.assigned_to['email']` and `bug.assigned_to_detail['email']` as well). Not having the address there breaks [did](https://github.com/psss/did).

I guess this is related to the recent upgrade of the bugzilla instance to Bugzilla5, however I don't know if the problem is in python-bugzilla, or in the bugzilla instance.

**Comment by crobinso** [comment]
Thanks for the report. I'm guessing you aren't logged in. Add bz.ensure_logged_in() in your code to catch this case, but you will need to either do a 'bugzilla login' to cache a login token, or setup API keys: https://blog.wikichoon.com/2019/01/python-bugzilla-bugzilla-50-api-keys.html

**Comment by olysonek** [comment]
Huh, `bugzilla login` did the trick. Thanks a lot for the quick response!
