### ISSUE TITLE
[RFE] bugzilla login should suggest using API key instead

### ISSUE THREAD

**Issue by tomato42** [python-bugzilla/python-bugzilla#93]
Te default authentication mode that `bugzilla login` uses are regular HTTP cookies. At least for bugzilla.redhat.com that means that they expire after few days, requiring logging once more, *after* a command that was using python-bugzilla failed. That's a bad user experience.

When `bugzilla login` notices that the instance it is connecting to is  Bugzilla 5, it should suggest to the user the use of API key instead of the HTTP cookies.

something like `bugzilla login --api-key` that asks for the API key and creates necessary configuration files would likely be most user friendly (short of generating the API key automatically).

**Comment by crobinso** [comment]
Upstream there is a `bugzilla login --api-key` option, which will prompt for an API key, and save it to ~/.config/python-bugzilla/bugzillarc. There's more mentions in the docs of API key bits now including a warning in --help.

The step further would be to explicitly fail if bugzilla login() doesn't even return a token value, or just unconditionally warn if 'bugzilla login' saves a token value. I'd take patches for those

**Comment by crobinso** [comment]
Now I have pushed a commit also doing what you suggest, adding this message after 'bugzilla login' for bugzilla >= 5.0

'Token usage is deprecated. Consider using bugzilla API keys instead.

Thanks for the suggestion!

**Comment by hroncok** [comment]
Hello. I see this message often but I have no idea what shall I do.

I'd like to consider using bugzilla API keys instead, but the message does not give any hints: Where do I look for more information?

**Comment by crobinso** [comment]
`man bugzilla` has some info, or this page: https://blog.wikichoon.com/2019/01/python-bugzilla-bugzilla-50-api-keys.html

**Comment by hroncok** [comment]
Thanks.
