### ISSUE TITLE
RFE: Option for 'minor_update' to not send email

### ISSUE THREAD

**Issue by wmealing** [python-bugzilla/python-bugzilla#94]
I have the option to 'not send email as this is a minor update" option in the Red Hat bugzilla, I'd like to be able to use this from the command line.

Is this something that I can be set with a CLI option or is it a field in can trigger? If not, please consider this as a feature request.

Thanks in advance.

**Comment by crobinso** [comment]
I was going to say 'this isn't supported by the API', but apparently it is nowadays! Not in any released bugzilla version that I can see, but in bugzilla git and in the bugzilla.redhat.com instance. You can use it right now via the cli:

  bugzilla modify $BUGNUM --field=minor_update=1 ...

But we should add a proper option and API support for it

**Comment by wmealing** [comment]
Thank you ! This will save me quite a lot of time !

**Comment by JacobCallahan** [comment]
This would be nice to have in the base arguments or for specific subcommands like modify.

**Comment by crobinso** [comment]
FWIW since I repeatedly struggle to understand upstream bugzilla git branch naming, here's the commit where this was added to upstream bugzilla, and where it's apparently in release 5.1.2 even though I can't find it in the docs:

https://github.com/bugzilla/bugzilla/commit/1d96fa1

**Comment by crobinso** [comment]
Actually 5.1.2 isn't even an official release or something, so this is still basically git only AFAICT

**Comment by wmealing** [comment]
Which is super strange, I didnt' expect the redhat bugzilla to be running a git release.

**Comment by crobinso** [comment]
They technically aren't, but they backported this particular patch. redhat bugzilla has a lot of custom changes

**Comment by JacobCallahan** [comment]
In the meantime, a flag could be added for minor updates (--minor) which simply adds 'minor_update=1' to the command's fields.

**Comment by crobinso** [comment]
FYI I filed a bug with mozilla about why minor_update is missing from the published docs, maybe that will clarify if/when it will officially land in a release: https://bugzilla.mozilla.org/show_bug.cgi?id=1608712

**Comment by thrasher-redhat** [comment]
Is there a way to do this in python with `build_update()`?  I'm not quite sure how the underlying update dict would match up to `--field=minor_update=1`.  Would something like the following example work?

    update = bzapi.build_update(comment=comment_body, comment_private=True)
    update["comment"]["minor_update"] = True
    bzapi.update_bugs(bug.id, update)

**Comment by crobinso** [comment]
@thrasher-redhat The latter case should be it
