### ISSUE TITLE
Add support for agile_pool.name bug field in rhbugzilla

### ISSUE THREAD

**Issue by thozza** [python-bugzilla/python-bugzilla#98]
Red Hat Bugzilla now contains Agile-related fields like agile_pool.name field and others (https://bugzilla.redhat.com/page.cgi?id=fields.html#agile_pool.name and https://bugzilla.redhat.com/rest/field/bug/agile_pool.name). Currently I didn't find a way to get value of this field for a specific bug using python-bugzilla API.

If possible, please add support to read and modify this field.

Thanks!

**Comment by crobinso** [comment]
Thanks for the report. Do you have an example bug number with this field set?

**Comment by thozza** [comment]
Hi.
Example is here: https://bugzilla.redhat.com/show_bug.cgi?id=828865. Basically any bug in RHEL-8 product has it. Unfortunately I don't think that it is publicly visible.

**Comment by crobinso** [comment]
You'll need to find a working XMLRPC API call and the I can work backwards to let you know how to do it. Maybe file a bug at bugzilla.redhat.com against class=Community product=Bugzilla and ask if that field is accessible over xmlrpc

**Comment by thozza** [comment]
Thanks. Done -> https://bugzilla.redhat.com/show_bug.cgi?id=1712018

**Comment by crobinso** [comment]
Okay from that bug I see the field name is just 'pool' in the API. So if you are using getbugs or query APIs, add extra_fields=["pool"] and it should be returned. If you are using the command line, use --outputformat with %{pool} in it and it should pop up. Please reopen if that doesn't work
